// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@3.1.0_vite@7.2.2_@types+node@24.9.2_jiti@2.6.1_lightningcss@1.30.2_terse_4458926f64a937b15a9777127e6b913b/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@3.1.0_vite@7.2.2_@types+node@24.9.2_jiti@2.6.1_lightningcss@1.30.2_terse_4458926f64a937b15a9777127e6b913b/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.8.2_magicast@0.5.1_nuxt@4.2.1_@biomejs+biome@2_86c681ad1c4e268732d9ec20eccc9e77/node_modules/@nuxt/content/dist/runtime/plugins/ws.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.8.2_magicast@0.5.1_nuxt@4.2.1_@biomejs+biome@2_86c681ad1c4e268732d9ec20eccc9e77/node_modules/@nuxt/content/dist/runtime/legacy/plugins/documentDriven.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.1_@biomejs+biome@2.3.4_@parcel+watcher@2.5.1_@types+node@24.9.2_@vue+compiler-_fc4feb61bf8dd2ac490c958000ccdeff/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
